{
 "title": "Blackbox-exporter",
 "description": "Status page",
 "tags": [
  "blackbox_exporter",
  "status"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(probe_http_status_code, project)"
    }
   },
   {
    "name": "target",
    "label": "target",
    "query": {
     "query": "label_values(probe_success, target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Responce time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "probe_duration_seconds{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success{})" }
   ]
  },
  {
   "title": "Detailed Info",
   "type": "table",
   "gridPos": { "h": 37, "w": 20, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "probe_duration_seconds{project=~\"$project\"}"
    },
    {
     "expr": "probe_success{project=~\"$project\"}"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success{} == 1)" }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success{} == 0)" }
   ]
  },
  {
   "title": "Instance status percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success{} == 1)", "legendFormat": "Success status instances" },
    { "expr": "count(probe_success{} == 0)", "legendFormat": "Failed status instances" }
   ]
  }
 ]
}